### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by thanospmc** [wyldckat/cgnsToFromFoam#1]
Hi Bruno, I cannot seem to make it compile. Is there something missing from the instructions? Apologies if this is something obvious. Here is the error when running wmake all -j src (after I have sourced OF5):

```
Compiling enabled on 4 cores
wmake src
++ pwd
+ LIBCGNSOOHOME=/home/poulos/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0
+ '[' -e /home/poulos/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0 -a '!' -r /home/poulos/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0/platforms/linux64GccDPInt32Opt/lib/libcgnsoo3.a ']'
+ pushd /home/poulos/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0
~/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0 ~/OpenFOAM/cgnsToFromFoam/src
+ ./bootstrap
+ [ ! -r ./NEWS ]
+ [ ! -r ./THANKS ]
+ [ ! -r ./README ]
+ [ ! -r ./AUTHORS ]
+ [ ! -r ./ChangeLog ]
+ rm -rf aclocal.m4 autom4te.cache
+ aclocal -I config
./bootstrap: 30: ./bootstrap: aclocal: not found
+ libtoolize --force --copy
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/usr/share/aclocal/libtool.m4'
libtoolize:   '/usr/share/aclocal/ltoptions.m4'
libtoolize:   '/usr/share/aclocal/ltsugar.m4'
libtoolize:   '/usr/share/aclocal/ltversion.m4'
libtoolize:   '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.in,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
+ autoheader
./bootstrap: 32: ./bootstrap: autoheader: not found
+ automake --add-missing --copy
./bootstrap: 33: ./bootstrap: automake: not found
+ autoconf
./bootstrap: 34: ./bootstrap: autoconf: not found
+ ./configure --prefix=/home/poulos/OpenFOAM/cgnsToFromFoam/src/libcgnsoo_3.0/platforms/linux64GccDPInt32Opt --with-CGNSLIBHOME=/usr
./Allwmake: line 22: ./configure: No such file or directory
+ CORES=4
+ make -j 4
make: *** No targets specified and no makefile found.  Stop.
+ make install
make: *** No rule to make target 'install'.  Stop.
+ popd
~/OpenFOAM/cgnsToFromFoam/src
```

I am working on Ubuntu 16.04. 

Thanks!

**Comment by wyldckat** [comment]
Hi Thanos,

Sorry, I forgot to write in the README file that the packages for compiling were already installed, since it's pretty usual to install them when building OpenFOAM-related code.

Please install the package `build-essential` in your Ubuntu installation, e.g. by running:

```
sudo apt-get install build-essential
```

Please let me know if this fixes the issue. Because the applications `autoheader`, `automake`, `autoconf` and `aclocal` are the ones missing and should be installed with the aforementioned package, if I'm not mistaken.

Best regards,
Bruno

**Comment by thanospmc** [comment]
Thanks for the fast response, Bruno. build-essential is installed (I have built OpenFOAM in my machine) but still have the issue. No worries for now, I'll try again a bit later and see how it goes.

**Comment by wyldckat** [comment]
I've finally managed to test this in one of my VMs where I test building OpenFOAM and indeed a package is missing from the installation instructions: `autoconf`

I'll update the instructions in a few minutes.

**Comment by wyldckat** [comment]
Done!

@thanospmc please let me know if this solves the problem for your as well!

**Comment by thanospmc** [comment]
Hi Bruno, indeed, that was the second problem that I encountered and I already tried after installing autoconf. Here is the log and the versions of the packages installed if you want to take a look.
[error.log](https://github.com/wyldckat/cgnsToFromFoam/files/1949887/error.log)
[packages.log](https://github.com/wyldckat/cgnsToFromFoam/files/1949888/packages.log)

Thanks a lot!

**Comment by wyldckat** [comment]
Hi Thanos,

This is a very strange error that you are getting... please try the following commands, from within the `cgnsToFromFoam` folder:

    wclean all src
    wmake all -j src

After these commands, does it still give the same exact error messages? Because this is a really strange compilation error, which should not have happened.

**Comment by thanospmc** [comment]
Thanks for looking into this, Bruno.

Still get the error. Maybe it has to do with my installation? I am using Bash on Windows (Ubuntu 16.04.4). However, I have compiled OpenFOAM before on this machine.

[compilation_error_2018-04-30.log](https://github.com/wyldckat/cgnsToFromFoam/files/1960480/compilation_error_2018-04-30.log)

**Comment by wyldckat** [comment]
I've tested just now installing OpenFOAM 5 Deb package on a brand new installation of Lubuntu 16.04 x86_64 inside a virtual machine, with the Lubuntu installation fully up-to-date. And the only issue was that I had to install the `git` package, because it wasn't installed along with the Deb package.

However, I did install the `open-vm-tool-desktop` package, which installed several packages that I wasn't expecting, so now I'm intrigued if one of those packages interfered with things...

On the other hand, I'm wondering if the Ubuntu installation under WSL has slightly different macro definitions, which would result in the compilation issues that you are having.

I will have to try this myself at my workstation at the office, to try and reproduce this issue. I guess I'll take the opportunity to also do some performance tests with our blueCFD-Core installations, namely our ports of OpenFOAM for Windows, with which I haven't tested yet building this toolkit.

I'll try to give you some more feedback on this, once I've found the time to look into this.

In the meantime, did you by any chance add other repositories to your Ubuntu installation? For example, some Science repositories that provide more recent HDF5 or CGNS libraries?

**Comment by thanospmc** [comment]
Thanks for taking such a close look! I have not added any other repository
for the HDF5 and CGNS libraries. Could you point to one of the repositories
to which you are referring?

Thanos

**Comment by wyldckat** [comment]
OK, if you didn't add any repositories for HDF5 or CGNS, then there is no need to worry. These two libraries are already provided in the default repositories that Ubuntu uses.

I'll try to look into this during this week at the office.

**Comment by wyldckat** [comment]
OK, I have good news and not so good news... the good news are that I was able to compile `cgnsToFromFoam` on Ubuntu running on Windows 10 WSL... but the not so good news is that I was not able to reproduce the same error(s) that you are getting.

Here are the steps I took, after having Ubuntu up and running:

1. Updated Ubuntu:

    ```
    sudo apt update
    sudo apt upgrade
    ```

2. Installed OpenFOAM 5 by following the instructions given here: https://openfoam.org/download/5-0-ubuntu/ - although I had to do a workaround to properly install the Deb packages, because SourceForge.net was down for me at the time of installation... fortunately I was able to quickly get a mirror URL for the two Deb packages.

3. I then did the following commands:

    ```
    sudo apt install libhdf5-dev libcgns-dev autoconf git
    mkdir -p $FOAM_RUN
    run
    cd ..
    git clone https://github.com/wyldckat/cgnsToFromFoam.git
    cd cgnsToFromFoam
    git checkout OF5x
    wmake all -j src
    sudo apt-get install build-essential
    wmake all -j src
    wmake -j applications/utilities/mesh/conversion/cgnsToFoam
    ```

And that was it! I was ready to use `cgnsToFoam` without problems.


That said, I was now thinking of the next step... my guess that is that you have installed something else besides OpenFOAM and tampered with the shell environment. You can check this by running:

```
wmUnset
export
```

Then the output shown on screen should reveal anything that isn't OpenFOAM-related on the shell environment, such as any build options.

In addition, I've pinpointed a possible critical point of failure: the `PATH` environment variable is seriously contaminated with Windows' mounted paths, which means that commands such `cmd.exe` will work... which may be another reason for the problems you're having, e.g. due to Windows binaries getting picked up by the scripts that are trying to build our custom code.

**Comment by thanospmc** [comment]
Thanks for taking a look, Bruno. I don't think I have something tampering
with the shell although I cleaned the PATH variable but to no effect. I am
not sure if this is worth looking into it further, I'll try on another
Ubuntu installation (not WSL).

You can reject and close, I believe. Thanks again.

Thanos
